Fix for https://wordpress.org/support/topic/users-whove-unsubscribed-still-get-emails-in-a-roundabout-way/
Miller-Media/send-emails-with-mandrill pull request #2
Opened 2018-08-13 17:50 UTC by pugwonk

I'm not sure this is, because there are some rejection reasons that rightfully should cause the whole batch to be rejected (e.g. invalid sender). But I'm not sure the right answer here is to send emails via the original wp_mail function instead. If you ask me, this plugin should probably never send things via wp_mail.

2018-08-22 04:39 UTC, MillerMedia commented
Adding @mike-mm here as a reviewer. Mike, this is based on a thread from the WordPress forum here: https://wordpress.org/support/topic/users-whove-unsubscribed-still-get-emails-in-a-roundabout-way/#post-10611107 ... thanks @pugwonk for the PR! We are reviewing.

2018-08-23 16:34 UTC, mike-mm requested changes
@pugwonk 
I'm hesitant to approve this change as it is, simply because as you put it yourself:

"...this isn’t quite ideal, because there are other reasons the mail might be rejected (e.g. invalid-sender) which will apply to every single recipient in the list and probably ought to cause the mail to be sent again with wp_mail."

If you feel like further updating this with the logic to handle the "invalid-sender" scenario, that would be super helpful. Thank you!

2018-08-23 18:05 UTC, pugwonk commented
Fair point - part of the reason I didn't do this is because I think that it would honestly be better _never_ to send emails using the built in wp_mail instead. I remember when I first used this plugin it was rather confusing working out whether it was operational or not, just because I still got the emails anyway. How would you feel about just pulling the whole send-via-wp_mail feature?

2018-08-29 17:11 UTC, douglsmith commented
> I think that it would honestly be better never to send emails using the built in wp_mail instead.

I completely agree with this. I'm using Mandrill so I have mail completely turned off on the server for the added measure of security and to lighten the server load. So if the plugin ever reverts to wp_mail, that means the mail just doesn't get sent at all.

2018-08-30 17:30 UTC, mike-mm commented
@pugwonk, if you want to remove the wp_mail feature, that sounds fine to me. Go ahead and add that change, and I'll review and approve it.

2018-08-30 17:48 UTC, pugwonk commented
Roger, will do. Might be a couple of weeks.

2020-08-26 22:46 UTC, MillerMedia commented
Wanted to bump this issue. We are in the process of closing out stale PRs. @pugwonk if you still want to make this change, feel free to submit an update and we will review. Thanks!

2020-08-26 22:50 UTC, pugwonk commented
> Wanted to bump this issue. We are in the process of closing out stale PRs. @pugwonk if you still want to make this change, feel free to submit an update and we will review. Thanks!

Oh dear yes, my "couple of weeks" claim was a bit optimistic. I'm afraid I'm not going to be able to do this in the foreseeable future (I blame Coronavirus) but if you leave it for the moment I will be able to get to it eventually. I also won't be offended if you kill it given that it's two years old. :)

2026-04-29 21:54 UTC, closed without merging